apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: gitops-repo
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAuhrhPBmDsKUWXDZeZADgeA+KuX82hHSypHuUi2Oz72VI1DlB
    aLdht0KlER8qM1395LgGaA5K+QNJ9AfVpBMnPO2S54l0cnheCU2lT9rc/emtDEWk
    8l+v9KJI2hnD8hoUnNZtRB3ujmU9uEyTP8UXFbkKlVT2c0FTR++p8P/rTo1V4J19
    BLcrEq684isqNfCkt5JLFSnAz+N2tE8SdfVYq805e6oST6gUi4Ffgq8BM7ri39QU
    BiWN/BI6n5v1Lazak34+NiR+I5xKwYBiDGQ6v9mEso8w9knDvsWNHW2kf4iZV3WV
    vDHwy7V60rnvB1TgocL6+otIFF4+64uRpySoqsQ0o0DmXcs6zOeVnxd/QhDlVsE2
    719zeNlzeQODRyuqBdiNfNUT0DnbG911+op402Ddu2aeSNBb4n8LW4McC9x3aWpZ
    f/j7afGD3feHKLrIJCX8suWmS3Wv4Q90iZiyG9YzdfBj8g72yQ+6m92h6QddOZjr
    mDzi6JQIfhAsCJQFnOur5EUDh5zCvTk4s5VGvgu6kxO1ZvVF0RAbIJX22s9fjeTZ
    pCwTEQg0UU7fAGNDKWDwjk0OmUOXaum5OtcU0NIwdeWQJ5RUt8HA0FbQKfC+WD5C
    NZMsQzcvzfRX8oFefHGItpfHy6Pz4JpGgKIBhzAjTTSe1h2Pxvan7tQB580CAwEA
    AQKCAgEAr1qadV15Fx1GZ1aXM9UbrCTAyq3R+ZZXqOIEgh5MsboWmFjmh7uap+l0
    zSA3TDU5AKRg7PTisaTmrrgfFj0x0JftvppmjWFbAZsWs5p+dgUTF6gbloCQs4mh
    6VczqM/oMitcwz0MxUEhmaEVcZXMfZxgG3r1yH158iMhVkJdPiOwEjdyT9ojDLR2
    pwiS+kYnfgyrEGLKGVezRovm0hx+E0sI6bvDCylNSnF5RBKPqGVkVhBnWa9TDHtE
    n5V8vC/NuAHQroVOEVG3ooHMYO6j6JcVEIYZVUcF2KAdqefggoZ8LctObggEYn06
    IIovbhIMon6sqxxHq2FuGdTlRb8l6DrjyvL//GVPUFFvmOUNq10w5QSZ1pQglb2J
    SDaSl4St+ysTaI3n6y2aAUOw0A7cctu+A1lD+0nJu0e5KS8/yCyl4MAgKo5bb+iW
    RIWNXcAuaV+ousH/7AOsZWZbFo3PCQ6/B3zTMdu9fELEsSCbpYwbBBi6mMDwBTjQ
    8a1mIUinzT+9Q9o8K0s8zg+ikyqNQA+OC9oD0RAOMMlkruHvjZogdR0j9562Akif
    sbZogfnSIgY8uHmhUYTn1/QWmG19IUEu5G/CO+exjFZ+VnjDHDwO4Ji4usRTcdcD
    NIQi/KOyDuNi+WEQrwisFU1Vo/IPnlCqiWt3I5nXDm4IrTLrDSECggEBAMBwQmEa
    Pw6uJl38Q3JFXiTnI4kcDIRNsanH41SuD64KSu1sDERe4ck6npOD5v1m2rpfIckS
    aXoLe+cONgjAHtZWbkr6k1kihk3NacZzaHHpQ7IkUvYJZrruDL5EcmeGFzbbKn6R
    U9XKeqw8kUo5au4a83msFZq3GkzG3i3EycqVKHCjD5AmYWUOWf2GPrv1NokaPCsZ
    Tg3IvGcrwYvwIsxw+Z8NvArxYH5q9X1rB9bJfFizm3bU1m8NkmAhZFj1E0ps0Yf6
    QjdkW4S4JiXRGRG7bj8bCn+vvVQj6tvaVmKg2MhQEND0Z7E4P1SfpyrbyRaShwLm
    PsXEzKzlkDqur9UCggEBAPeTFkC3IgsmCtSz3CaLUF177OCYLAxW7Pk90x0/8Vx6
    JnHd9kQvDfc4SLstIfVqN6n4GfCP8gCBtH9ad1DwkUpocltCeUwzJ/wwak0E/tDb
    SdgAFJKgZYIt6DA8Z1UqnPxGLmaMO+aE6W+jrz21pr+D1Tg5Ev4Ax/6B2f9ELrG4
    srNuIu72G7Xz4sPVoiTjbP/awB4T9xe0upWRkNWjvQh/1afmS4YCkFgpr7OUDHA3
    xtu12ryMUlpRb6bpyq1YWtdQqtNz6TokbyA/YTGdpHPbg9HaDnqeH4DUtcPu6Ymx
    PLWfICpSZJoKK4ZSC1OnZr/JiVkZPCvTQFh66eEBzBkCggEAe0RtgL3LPqAXO4Tn
    vz7n+0OD48Pv0J/j+hlsaUXGDXnSXRslEHamsru18FBBmnhUC6X8gkwk/GR2zZ6w
    xhIqrqlWpPi1ghc3aIb4BoLOmIkPMAFMkwWapIrv5sD5d47RN/ZT1hdJWF0HD2UM
    vDrjX/ork/jDLgOz+RI6J58yk23QJbaNtYygPpde1aM0dDmy4UfI2uKuuO2ooX3J
    0NXVtJd5joTBu1C6ur/Q2LHCp7cQy9Dg+NGFOkW7SZCaMtFptfbWkP+hgtHqPa2n
    4fl60Xz6Nbogk4IDCO6o9oN5alwWANooq3CjK0YYayCJeE6pFKhvi0/pTc2uPeIe
    7TgQsQKCAQAk7hvzq124rAQRloLQfReP2lyLZCet74mJ5F8JjfBDCzWQ5rtFkH9U
    0WCIC0N1iFKlWA0GhXJkAPUbyjLiMAB8SPhGBLRzWW4tgEtbEdOw9AUf42MuPB7o
    PFDWYSxI2AJy30Uspt6IlGr97DzHx8EH8HJt4JWkrhknLdeG7HTKrfJ6MYOkgbHA
    gpDhBY0aU5J+1/Kwienh72OlzAD+3V3lVqxYT1IUu20suYssDnmMg8V2ILpwRb5D
    GsK880L4eKWUWMQiprezpJuvA8VL0WgmoCgZtZ1TTSMF5LT4dTsA/x8/OG1j4sZ+
    8+VqM/Lcl6wMD9QdJlaDcw+2Ix+gINSBAoIBABsbmdLpTE7N4JmeIXzHr9pHoiSV
    //lTh4hfvi+9RzaxDVh6I4ETS605Mp+T/Jm84a4crmgpn37YoJBxOoxAsOxl/zcB
    ZKl6IhLEmIpQtCbg/6BSGwNG/a6HYU0D1ytoAR5c71jUzz6f9ZJv6i2Sq3TRm6bk
    uYcDwdr4qTWKw3DQsp2/SUPhsWsm1lu8UIJx8fJEhCfaD1ytFWHZvQIW9B/sHi28
    FbPVRtllvgyktLt2qGYBNg8Kb9xTVChHz51+vGXS2Q1GDJVuTN0epvKtEi4ZHFl7
    cxAg2vd3bi2vzIL+77Lj+N9Vn+uOxkHudnYniTGZPwxnGmySV5j0RYiRU1g=
    -----END RSA PRIVATE KEY-----
  identity.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6GuE8GYOwpRZcNl5kAOB4D4q5fzaEdLKke5SLY7PvZUjUOUFot2G3QqURHyozXf3kuAZoDkr5A0n0B9WkEyc87ZLniXRyeF4JTaVP2tz96a0MRaTyX6/0okjaGcPyGhSc1m1EHe6OZT24TJM/xRcVuQqVVPZzQVNH76nw/+tOjVXgnX0EtysSrrziKyo18KS3kksVKcDP43a0TxJ19VirzTl7qhJPqBSLgV+CrwEzuuLf1BQGJY38Ejqfm/UtrNqTfj42JH4jnErBgGIMZDq/2YSyjzD2ScO+xY0dbaR/iJlXdZW8MfDLtXrSue8HVOChwvr6i0gUXj7ri5GnJKiqxDSjQOZdyzrM55WfF39CEOVWwTbvX3N42XN5A4NHK6oF2I181RPQOdsb3XX6injTYN27Zp5I0FvifwtbgxwL3Hdpall/+Ptp8YPd94cousgkJfyy5aZLda/hD3SJmLIb1jN18GPyDvbJD7qb3aHpB105mOuYPOLolAh+ECwIlAWc66vkRQOHnMK9OTizlUa+C7qTE7Vm9UXREBsglfbaz1+N5NmkLBMRCDRRTt8AY0MpYPCOTQ6ZQ5dq6bk61xTQ0jB15ZAnlFS3wcDQVtAp8L5YPkI1kyxDNy/N9FfygV58cYi2l8fLo/PgmkaAogGHMCNNNJ7WHY/G9qfu1AHnzQ==
  known_hosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
